import type { MetadataRoute } from "next";

import {
  SECTIONS,
  SECTION_PAGES,
  TRUST_PAGES,
  absoluteUrl,
  sectionHref,
  sectionPageHref,
} from "@/lib/site";

/**
 * sitemap.xml.
 *
 * Every entry is derived: section roots from `SECTIONS`, their sub-pages from
 * `SECTION_PAGES`, the site-level trust pages from `TRUST_PAGES`. The only
 * literal here is "/" — the hub. A tool that exists in the header is in the
 * sitemap by construction, and a page added to the config appears in both at
 * once.
 *
 * The consequence worth stating: a section route that is not in
 * `SECTION_PAGES` is an orphan — no sitemap entry, no footer link. That is
 * deliberate. A sitemap generated by convention (`SECTIONS × ["methodology",
 * …]`) would have submitted /trades/methodology, which does not exist, and
 * submitting 404s costs more crawl trust than the missing page costs traffic.
 *
 * Absolute URLs come from `SITE_URL` via `absoluteUrl`, never a hardcoded
 * domain, so a preview deployment submits its own origin.
 *
 * `lastModified` is the deployment time, which is the honest answer here: the
 * shell changes when it is redeployed. Pages whose numbers come from dated rule
 * sets should be driven by rule verification dates instead — but a fake
 * freshness stamp is detected by Google and by readers, and this file will not
 * invent one.
 *
 * NOT covered, by design: the dynamic routes
 * `/property/counties/[state]/[county]` and `/trades/contracts/[state]`. Those
 * enumerate from rules data owned by their sections, and the section owners
 * should emit them with `generateSitemaps` rather than have the shell guess at
 * which counties and states have shipped.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  const hub: MetadataRoute.Sitemap = [
    { url: absoluteUrl("/"), lastModified, changeFrequency: "weekly", priority: 1 },
  ];

  const sections: MetadataRoute.Sitemap = SECTIONS.flatMap((section) => [
    {
      url: absoluteUrl(sectionHref(section)),
      lastModified,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    ...SECTION_PAGES[section.slug].map((page) => ({
      url: absoluteUrl(sectionPageHref(section, page)),
      lastModified,
      // A tool route changes when its rules do; a trust page when the process
      // does. Neither is weekly, and claiming otherwise is noise.
      changeFrequency: page.trust ? ("monthly" as const) : ("weekly" as const),
      priority: page.trust ? 0.5 : 0.8,
    })),
  ]);

  const trust: MetadataRoute.Sitemap = TRUST_PAGES.map((page) => ({
    url: absoluteUrl(page.href),
    lastModified,
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  return [...hub, ...sections, ...trust];
}
