import type { MetadataRoute } from "next";

import { counties } from "@/engines/property";
import { STATE_IDS } from "@/engines/trades";
import { listPosts, toolGuidesHref, toolsWithPosts } from "@/lib/content";

import {
  SECTIONS,
  SECTION_PAGES,
  SITE_URL,
  TRUST_PAGES,
  absoluteUrl,
  sectionHref,
  sectionPageHref,
} from "@/lib/site";

/**
 * sitemap.xml.
 *
 * Every entry is derived: section roots from `SECTIONS`, their sub-pages from
 * `SECTION_PAGES`, the site-level trust pages from `TRUST_PAGES`. The only
 * literal here is "/" — the hub. A tool that exists in the header is in the
 * sitemap by construction, and a page added to the config appears in both at
 * once.
 *
 * The consequence worth stating: a section route that is not in
 * `SECTION_PAGES` is an orphan — no sitemap entry, no footer link. That is
 * deliberate. A sitemap generated by convention (`SECTIONS × ["methodology",
 * …]`) would have submitted /trades/methodology, which does not exist, and
 * submitting 404s costs more crawl trust than the missing page costs traffic.
 *
 * Absolute URLs come from `SITE_URL` via `absoluteUrl`, never a hardcoded
 * domain, so a preview deployment submits its own origin.
 *
 * `lastModified` is the deployment time, which is the honest answer here: the
 * shell changes when it is redeployed. Pages whose numbers come from dated rule
 * sets should be driven by rule verification dates instead — but a fake
 * freshness stamp is detected by Google and by readers, and this file will not
 * invent one.
 *
 * The two prerendered dynamic routes — `/property/counties/[state]/[county]`
 * and `/trades/contracts/[state]` — are enumerated from the SAME exports their
 * `generateStaticParams` reads (`counties`, `STATE_IDS`), so the sitemap and
 * the build cannot disagree about which pages exist. They were previously
 * omitted "by design", on the theory that the section owners would emit them
 * with `generateSitemaps`; nobody did, and the result was seven prerendered,
 * internally-linked, fully-cited pages — five state contract-law pages and two
 * county appeal playbooks — that no sitemap ever declared. Omitting a real
 * page from the sitemap costs discovery; the guess this avoided was never the
 * risk, because the enumeration is imported rather than guessed.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();

  // `SITE_URL` rather than `absoluteUrl("/")`: the hub's own canonical tag
  // resolves to the bare origin with no trailing slash, and a sitemap that
  // declares a URL the page then canonicalises away is a self-inflicted
  // duplicate-content signal. One string, both places.
  const hub: MetadataRoute.Sitemap = [
    { url: SITE_URL, lastModified, changeFrequency: "weekly", priority: 1 },
  ];

  const sections: MetadataRoute.Sitemap = SECTIONS.flatMap((section) => [
    {
      url: absoluteUrl(sectionHref(section)),
      lastModified,
      changeFrequency: "weekly" as const,
      priority: 0.9,
    },
    ...SECTION_PAGES[section.slug].map((page) => ({
      url: absoluteUrl(sectionPageHref(section, page)),
      lastModified,
      // A tool route changes when its rules do; a trust page when the process
      // does. Neither is weekly, and claiming otherwise is noise.
      changeFrequency: page.trust ? ("monthly" as const) : ("weekly" as const),
      priority: page.trust ? 0.5 : 0.8,
    })),
  ]);

  const trust: MetadataRoute.Sitemap = TRUST_PAGES.map((page) => ({
    url: absoluteUrl(page.href),
    lastModified,
    changeFrequency: "monthly" as const,
    priority: 0.6,
  }));

  // The prerendered dynamic routes, enumerated from the same engine exports
  // their `generateStaticParams` uses. A county or state that has not shipped
  // is not in these arrays, so it cannot reach the sitemap.
  const countyPages: MetadataRoute.Sitemap = counties.map((county) => {
    const [state, slug] = county.countyId.split("-");
    return {
      url: absoluteUrl(`/property/counties/${state}/${slug}`),
      lastModified,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    };
  });

  const contractPages: MetadataRoute.Sitemap = STATE_IDS.map((state) => ({
    url: absoluteUrl(`/trades/contracts/${state}`),
    lastModified,
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  /*
   * Guides and the glossary.
   *
   * Enumerated from `listPosts()` and `toolsWithPosts()` — the same functions
   * `generateStaticParams` reads — so the sitemap cannot claim an article that
   * was not built, or miss one that was. A draft is excluded by `listPosts()`
   * itself and therefore never reaches here.
   *
   * An article's `lastModified` is its own `updatedAt`, not the deployment
   * time. It is the one date on this site that means something specific: the
   * day the page was last reviewed against its sources. Stamping a redeploy on
   * it would be the fake freshness the rest of this file refuses to emit.
   */
  const guideIndex: MetadataRoute.Sitemap = [
    { url: absoluteUrl("/guides"), lastModified, changeFrequency: "weekly", priority: 0.8 },
    { url: absoluteUrl("/glossary"), lastModified, changeFrequency: "monthly", priority: 0.6 },
  ];

  const guideClusters: MetadataRoute.Sitemap = toolsWithPosts().map((tool) => ({
    url: absoluteUrl(toolGuidesHref(tool)),
    lastModified,
    changeFrequency: "weekly" as const,
    priority: 0.7,
  }));

  const guides: MetadataRoute.Sitemap = listPosts().map((post) => ({
    url: absoluteUrl(post.href),
    lastModified: new Date(post.updatedAt),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  return [
    ...hub,
    ...sections,
    ...trust,
    ...countyPages,
    ...contractPages,
    ...guideIndex,
    ...guideClusters,
    ...guides,
  ];
}
