import type { Metadata } from "next";
import Link from "next/link";

import { getStateRules, STATE_IDS, untranscribedClauses } from "@/engines/trades";

import { AnswerBox, FactTable } from "@/components/ui";
import { usd } from "@/components/ui/format";

import ContractView from "@/components/trades/ContractView";

export const metadata: Metadata = {
  alternates: { canonical: "/trades/contract" },
  title: "Contract Template — State-Required Clauses, Cited",
  description:
    "Generate a home improvement contract template carrying the clauses your state requires for a job this size, each with its statute. Template, not legal advice. Free, no signup.",
};

/**
 * The contract generator.
 *
 * The tool itself only has something to show once an estimate is saved, so for
 * a first-time visitor — and for every crawler, which never has one — this
 * route used to render an h1, one sentence and an empty state: 49 words. The
 * explanation below is rendered unconditionally and comes from the same rules
 * files the generator reads, so it is accurate for a reader who has not built
 * an estimate yet and cannot drift from what the tool does.
 */

const link = "rounded-atlas underline underline-offset-4 hover:text-ink";

export default function ContractPage() {
  const states = STATE_IDS.map((id) => {
    const rules = getStateRules(id);
    const always = rules.requiredClauses.filter((clause) => clause.trigger === "always").length;
    return {
      id,
      name: rules.stateName,
      total: rules.requiredClauses.length,
      always,
      conditional: rules.requiredClauses.length - always,
      threshold: rules.homeImprovementThresholdCents,
      blocked: untranscribedClauses(rules).length,
    };
  });

  const clauseTotal = states.reduce((sum, state) => sum + state.total, 0);
  const blockedStates = states.filter((state) => state.blocked > 0);

  return (
    <div className="space-y-6">
      <div className="no-print space-y-6">
        <h1>Your contract template</h1>

        <AnswerBox>
          A home improvement contract carries different mandatory clauses in every state, and
          which ones apply turns on the job&rsquo;s own facts — contract price and down payment.
          Across the <span className="num">{states.length}</span> states encoded here that is{" "}
          <span className="num">{clauseTotal}</span> distinct required clauses, each generated with
          the statute that requires it.
        </AnswerBox>

        <p className="text-dim" style={{ maxWidth: "var(--measure)" }}>
          Clauses are selected from your state&apos;s rules and this job&apos;s facts — contract
          price and down payment. Every clause carries its statute.
        </p>
      </div>

      <ContractView />

      <div className="no-print space-y-6">
        <h2>How are the clauses chosen?</h2>

        <p className="text-dim" style={{ maxWidth: "var(--measure)" }}>
          By evaluating each state&rsquo;s trigger expressions against two facts about this job:
          the total contract price and the down payment. Some clauses apply to every job in the
          state; others switch on only above a dollar threshold, or only when the down payment
          exceeds a statutory cap, or only when the work is residential. Nothing here is a
          judgement call and nothing is generated by a language model — the same job facts in the
          same state produce the same document every time, which is what makes the output
          checkable against the statute rather than something you have to take on trust.
        </p>

        <h2>What does each state require?</h2>

        <p className="text-dim" style={{ maxWidth: "var(--measure)" }}>
          The threshold below is the contract price at which a state&rsquo;s home improvement
          rules begin to bite. &ldquo;Always&rdquo; clauses apply to every covered job;
          conditional ones depend on this job&rsquo;s numbers. Each state page sets out the clause
          list in full, with its statutory cite and what the clause has to say.
        </p>

        <FactTable
          caption="Required contract clauses by state"
          captionVisible
          rows={states.map((state) => ({
            key: state.name,
            value: (
              <>
                <span className="num">{state.always}</span> always ·{" "}
                <span className="num">{state.conditional}</span> conditional · threshold{" "}
                <span className="num">{usd(state.threshold)}</span> ·{" "}
                <Link href={`/trades/contracts/${state.id}`} className={`${link} text-ink`}>
                  {state.name} rules
                </Link>
              </>
            ),
            mono: false,
          }))}
        />

        <h2>Why does it sometimes refuse to produce a document?</h2>

        <p className="text-dim" style={{ maxWidth: "var(--measure)" }}>
          Because some states prescribe notice wording word for word — a right-to-cancel notice,
          a mechanics lien warning — and a paraphrase of a statutory notice is not that notice. Any
          state whose prescribed text has not been transcribed from the statute produces no
          document at all. Instead the tool names the clause, the statute and the URL the wording
          has to come from, so you know exactly what is missing.{" "}
          {blockedStates.length > 0 ? (
            <>
              Today that blocks{" "}
              <span className="num">{blockedStates.length}</span> of the{" "}
              <span className="num">{states.length}</span> states encoded:{" "}
              {blockedStates.map((state) => state.name).join(", ")}.
            </>
          ) : (
            <>No encoded state is blocked today.</>
          )}{" "}
          A contract that looks right and is not is worse than no contract, because it gets signed.
        </p>

        <h2>The generator sees three facts about your job, and no more</h2>

        <p className="text-dim" style={{ maxWidth: "var(--measure)" }}>
          The contract price, the down payment, and the cost of any special-order materials.
          That is the whole fact set the triggers evaluate against, which is why the same job
          always produces the same document — and it is also the boundary of what the tool
          can do for you. It does not know whether the deal was signed at a kitchen table or
          in your office, how old the homeowner is, whether they are married, whether the
          property is their homestead, or whether the work is an emergency repair. Every one
          of those changes what a state requires. Texas asks for both spouses&rsquo;
          signatures where the owner is married and the property is a homestead; California
          has a separate cancellation notice, with a longer window, for homeowners aged 65
          and over, and it is a distinct prescribed notice this ruleset does not model at
          all. Where a clause depends on a fact the engine cannot see, it fires on every job
          rather than guessing — over-inclusion, which is the safe direction, but it means
          the document can carry a notice your particular job did not need.
        </p>

        <h2>Transcribing the missing text would not unblock every state</h2>

        <p className="text-dim" style={{ maxWidth: "var(--measure)" }}>
          The statutes that prescribe wording usually prescribe how it appears: a minimum
          point size, boldface, capitals, a position on the front page, a signature and date
          belonging to the notice rather than to the contract, and in one case a duplicate
          form that has to detach from the document. Those requirements are recorded against
          each clause in the rulesets, and nothing here can render any of them yet — a
          12-point boldface notice printed at body size is not a compliant notice. So three
          of the blocked states need a renderer as well as a transcriber; only New York,
          whose single missing notice asks for bold face type and nothing more, would be
          cleared by transcription alone. Both halves are tracked in the{" "}
          <Link href="/trades/changelog" className={`${link} text-ink`}>
            changelog
          </Link>
          .
        </p>

        <h2>Is this legal advice?</h2>

        <p className="text-dim" style={{ maxWidth: "var(--measure)" }}>
          No. It is a template assembled from published statutory requirements, and the clause
          language has not yet been reviewed by a construction attorney — the{" "}
          <Link href="/trades/editorial-policy" className={`${link} text-ink`}>
            editorial policy
          </Link>{" "}
          makes that review a launch gate, and it has not been met. Have an attorney read the
          contract before you sign it or ask a customer to. What the tool can genuinely do is stop
          you sending a contract that is missing a clause your state requires, and show you the
          statute behind each one so the conversation with an attorney starts from the text.
        </p>

        <h2>Where does the job data come from?</h2>

        <p className="text-dim" style={{ maxWidth: "var(--measure)" }}>
          From the estimate you built in the{" "}
          <Link href="/trades" className={`${link} text-ink`}>
            takeoff sheet
          </Link>
          , saved in your own browser. Nothing is uploaded, there is no account, and the finished
          contract is never stored anywhere but on your device. The same estimate also drives the{" "}
          <Link href="/trades/invoice" className={`${link} text-ink`}>
            invoice
          </Link>
          , which is why the contract price, the estimate total and the invoice total are the same
          number to the cent.
        </p>
      </div>
    </div>
  );
}
